### PR TITLE
Ability to override Nethermind flags

### PR DESCRIPTION
**Pull request by naps62**
I need my Nethermind node to run the `Trace` module, as well as include additional values into `JsonRpc.EnabledModules`. Adding extra duplicate flags through `EC_ADDITIONAL_FLAGS`. This is the next best thing I could think of.

With this change, users should be able to add the whole `JsonRpc.EnabledModules` and `JsonRpc.AdditionalUrls` flags to `EC_ADDITIONAL_FLAGS`, and the script will fill in the default values if they're not present.
In this approach, it's up to make sure they still include the correct modules and urls that RocketPool requires by default

### CODE REVIEW

**Comment by naps62** [comment]
PS: I just realized this is `/bin/sh`, so I what I wrote doesn't actually work yet. I'll rework it

**Comment by jclapis** [comment]
Ok, I understand your need here. The only real issue present is that I use the `JsonRpc.AdditionalUrls` field to set up the `admin` route on localhost to listen for pruning requests; and as you mentioned:

> In this approach, it's up to make sure they still include the correct modules and urls that RocketPool requires by default

This is going to invariably cause some confusion and help in the Support channel. 

What I would like to do instead is add two new fields to the TUI: one for "Additional Enabled Modules" where you can throw `TRACE` and whatever else you need into the list of enabled modules, and an "Additional JSON RPC URLs" field that amends to the `admin` pruning URL but doesn't overwrite it. Let me put something together and I'll have you take a look.

**Comment by jclapis** [comment]
Ok @naps62 here you go: 
image

These two fields should let you do what you need. They preserve the default behavior when blank, and amend to it when not blank, so they don't require the user to know anything special about the RP requirements. Will that work for you?

**Comment by naps62** [comment]
@jclapis it works, and it actually was the first thing I attempted. ended up switching to this because I assumed you'd want the more general approach instead of adding specific fields to the UI, and because I wasn't sure if this was even possible for all ECs (I'm only familiar with Nethermind)

Anyway, good to know :+1: will this be available on the next release, I assume?

**Comment by jclapis** [comment]
> @jclapis it works, and it actually was the first thing I attempted. ended up switching to this because I assumed you'd want the more general approach instead of adding specific fields to the UI, and because I wasn't sure if this was even possible for all ECs (I'm only familiar with Nethermind)
> 
> Anyway, good to know +1 will this be available on the next release, I assume?

Yes, this will be in the next release. If this looks like it will work for you then feel free to close the PR.

**Comment by jclapis** [comment]
@naps62 Can you confirm if this is working to your needs?

**Comment by naps62** [comment]
It is. thank you!

**Pull request closed without merging**
