### PR TITLE
New metrics

### PR DESCRIPTION
**Pull request by 0xfornax**
Adding Governance and Smoothing Pool metrics as well as the peer count for some ECs (missing Nethermind).
image
image

### CODE REVIEW

**Comment by jclapis** [comment]
This is an outstanding start Fornax, thanks for tackling it. I have a few suggestions for v1.2:

- A dedicated EC member to the CPU Usage and RAM Usage charts
- 
- Standardize the RAM Usage chart to GiB instead of GB
- 
- I believe these two panels show the same thing, so the left one can probably be removed:
image

- Off the top of my head, I think unclaimed RPL and ETH should be put together since claiming them is the same operation - something like this (I made the background green when the threshold is >0.0001 instead of red since you can claim whenever now):
image

- The Smoothing Pool balance is probably better suited for the Rocket Pool Network Stats section, something like this:
image

Let me know if you agree / disagree with any of those and I'll be happy to take another look!

**Comment by 0xfornax** [comment]
Great feedback Joe!
I've implemented items 2, 3, 4, and 5 for all the dashboards. I still need to figure out which fields to use to show the CPU and RAM usage for the execution clients.

One question: I have received a few requests to add the total number of minipools that joined the smoothing pool, so users would be able to see an estimate of rewards per minipool. I initially didn't add that info to avoid the overhead of thousands of requests. Do you think I should add it? (maybe updating it once a day only?)

**Comment by jclapis** [comment]
> Great feedback Joe! I've implemented items 2, 3, 4, and 5 for all the dashboards. I still need to figure out which fields to use to show the CPU and RAM usage for the execution clients.
> 
> One question: I have received a few requests to add the total number of minipools that joined the smoothing pool, so users would be able to see an estimate of rewards per minipool. I initially didn't add that info to avoid the overhead of thousands of requests. Do you think I should add it? (maybe updating it once a day only?)

I wouldn't add the total number of minipools that joined the SP until Kane can make that a view in the contracts so we only need to run one call. I'll see if I can get him to add it for Atlas.

**Comment by jclapis** [comment]
Alright it's time, let's merge these up.

**Pull request merged**
